<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-21 14:27
=======
# Generated by Django 5.0.6 on 2024-06-25 12:19
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52

import data.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tel', models.CharField(max_length=31, verbose_name='telephone number')),
                ('adrs', models.CharField(max_length=63, verbose_name='adress')),
                ('adrs2', models.CharField(blank=True, max_length=63, verbose_name='second adress')),
                ('post', models.CharField(max_length=15, verbose_name='post code')),
                ('city', models.CharField(max_length=31)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-last_login'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('nb_org', models.IntegerField(verbose_name='maximum of co-organization')),
                ('nb_access', models.IntegerField(verbose_name='maximum of access')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('tel', models.CharField(max_length=31, verbose_name='telephone number')),
                ('adrs', models.CharField(max_length=63, verbose_name='adress')),
                ('post', models.CharField(max_length=15, verbose_name='post code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailBell',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mailbell', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('frequence', models.IntegerField(default=255)),
                ('fileshare', models.BooleanField(default=True)),
                ('changeoccur', models.BooleanField(default=True)),
                ('commentpost', models.BooleanField(default=True)),
                ('newmessage', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date_i', models.DateField(verbose_name='start date')),
                ('date_f', models.DateField(verbose_name='end date')),
                ('period', models.DurationField(verbose_name='duration')),
                ('type', models.CharField(choices=[('1', 'Type1'), ('2', 'Type2'), ('3', 'Type3'), ('4', 'Type4')], default='1', max_length=1)),
<<<<<<< HEAD
                ('con', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.contract', verbose_name='contract')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.organization', verbose_name='organization in charge')),
=======
                ('con', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='data.contract', verbose_name='contract')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='data.organization', verbose_name='organization in charge')),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['-date_i', '-date_f'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('content', models.FileField(upload_to=data.models.file_path)),
<<<<<<< HEAD
                ('is_commented', models.BooleanField(default=False)),
                ('is_boycotted', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.contract', verbose_name='contract')),
                ('exer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.exercise', verbose_name='exercise')),
=======
                ('last_update', models.DateField(auto_now=True)),
                ('is_template', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_commented', models.BooleanField(default=False)),
                ('is_boycotted', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data.contract', verbose_name='contract')),
                ('exer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data.exercise', verbose_name='exercise')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to=settings.AUTH_USER_MODEL)),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('colone', models.IntegerField()),
                ('text', models.TextField(max_length=4095)),
                ('is_treated', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='data.comment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.file')),
            ],
            options={
                'ordering': ['file', 'parent'],
=======
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_on_queue', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='data.comment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.file')),
            ],
            options={
                'ordering': ['file'],
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='org',
<<<<<<< HEAD
            field=models.ManyToManyField(to='data.organization', verbose_name='co-organization'),
=======
            field=models.ManyToManyField(related_name='contracts', to='data.organization', verbose_name='organizations'),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
        ),
        migrations.AddField(
            model_name='customuser',
            name='org',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='data.organization', verbose_name='organization'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='data.organization', verbose_name='organization'),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
        ),
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='access', serialize=False, to='data.file')),
<<<<<<< HEAD
                ('org', models.ManyToManyField(related_name='access', to='data.organization')),
                ('user', models.ManyToManyField(related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgConRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Role1'), ('2', 'Role2'), ('3', 'Role3'), ('4', 'Role4')], default='4', max_length=1)),
                ('nb_acct', models.IntegerField(verbose_name='number of account related')),
                ('exer_create', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_right', to='data.contract', verbose_name='contract')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_right', to='data.organization', verbose_name='organization')),
=======
                ('is_public', models.BooleanField(default=False)),
                ('org', models.ManyToManyField(related_name='file_access', to='data.organization', verbose_name='Organization')),
                ('user', models.ManyToManyField(related_name='file_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgConRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Approver'), ('C', 'Contributer'), ('O', 'Observer'), ('S', 'Selfdefined'), ('U', 'Undefined')], default='U', max_length=1)),
                ('nb_acct', models.IntegerField(verbose_name='number of account related')),
                ('is_principal', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_rights', to='data.contract', verbose_name='contract')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_rights', to='data.organization', verbose_name='organization')),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['org', 'con'],
                'unique_together': {('org', 'con')},
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='OrgExerRights',
=======
            name='OrgExerRight',
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.BooleanField(default=False)),
                ('output', models.BooleanField(default=False)),
                ('graph', models.BooleanField(default=False)),
                ('rewrite', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_right', to='data.exercise')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exer_right', to='data.organization')),
=======
                ('exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_rights', to='data.exercise', verbose_name='exercise')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exer_rights', to='data.organization', verbose_name='organization')),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['org', 'exer'],
                'unique_together': {('org', 'exer')},
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserConRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_right', to='data.contract', verbose_name='contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_right', to=settings.AUTH_USER_MODEL)),
=======
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='data.file')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_to', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['from_user', 'to_user', 'file'],
                'unique_together': {('from_user', 'to_user', 'file')},
            },
        ),
        migrations.CreateModel(
            name='UserConRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Approver'), ('C', 'Contributer'), ('O', 'Observer'), ('S', 'Selfdefined'), ('U', 'Undefined')], default='U', max_length=1)),
                ('is_chief', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rights', to='data.contract', verbose_name='contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_rights', to=settings.AUTH_USER_MODEL)),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['con', 'user'],
                'unique_together': {('con', 'user')},
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserExerRights',
=======
            name='UserExerRight',
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.BooleanField(default=False)),
                ('output', models.BooleanField(default=False)),
                ('graph', models.BooleanField(default=False)),
                ('rewrite', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_right', to='data.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exer_right', to=settings.AUTH_USER_MODEL)),
=======
                ('exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rights', to='data.exercise', verbose_name='exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exer_rights', to=settings.AUTH_USER_MODEL)),
>>>>>>> c0c20ab1fe9b10769c376b143edde9448a270d52
            ],
            options={
                'ordering': ['user', 'exer'],
                'unique_together': {('user', 'exer')},
            },
        ),
    ]
