<<<<<<<< HEAD:data/migrations/0004_alter_invitation_expired_at.py
# Generated by Django 5.0.6 on 2024-07-25 09:57
========
# Generated by Django 5.0.6 on 2024-07-24 09:44
>>>>>>>> 127b85ad4f7d3be3cb60a0a1ba480950930c3fdc:data/migrations/0002_alter_invitation_expired_at.py

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:data/migrations/0004_alter_invitation_expired_at.py
        ('data', '0003_notification'),
========
        ('data', '0001_initial'),
>>>>>>>> 127b85ad4f7d3be3cb60a0a1ba480950930c3fdc:data/migrations/0002_alter_invitation_expired_at.py
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
<<<<<<<< HEAD:data/migrations/0004_alter_invitation_expired_at.py
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 9, 57, 29, 44209, tzinfo=datetime.timezone.utc)),
========
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 11, 44, 9, 432523)),
>>>>>>>> 127b85ad4f7d3be3cb60a0a1ba480950930c3fdc:data/migrations/0002_alter_invitation_expired_at.py
        ),
    ]
