# Generated by Django 5.0.6 on 2024-06-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbell',
            old_name='changeoccur',
            new_name='newchange',
        ),
        migrations.RenameField(
            model_name='mailbell',
            old_name='commentpost',
            new_name='newcomment',
        ),
        migrations.RenameField(
            model_name='mailbell',
            old_name='fileshare',
            new_name='newfile',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_to_deal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='nb_org',
            field=models.IntegerField(verbose_name='maximum of organization'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='org',
            field=models.ManyToManyField(related_name='cons', to='data.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='con',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exers', to='data.contract', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exers', to='data.organization', verbose_name='organization in charge'),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='last update'),
        ),
    ]
