# Generated by Django 5.0.6 on 2024-10-17 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 13, 10, 16, 261856, tzinfo=datetime.timezone.utc)),
        ),
    ]
