# Generated by Django 5.0.6 on 2024-12-09 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_invitation_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 13, 24, 48, 485959, tzinfo=datetime.timezone.utc)),
        ),
    ]
