# Generated by Django 5.0.6 on 2024-07-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_customuser_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(choices=[('E', 'Exercise'), ('U', 'User'), ('F', 'File'), ('C', 'Comment'), ('T', 'Contract')])),
                ('event', models.CharField(choices=[('C', 'CREATE'), ('U', 'UPDATE'), ('D', 'DELETE')])),
                ('message', models.CharField(max_length=1023)),
                ('trigger_time', models.DateTimeField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
