# Generated by Django 5.0.6 on 2024-07-25 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 9, 57, 29, 44209, tzinfo=datetime.timezone.utc)),
        ),
    ]
