# Generated by Django 5.0.6 on 2024-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_orgconright_nb_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='org',
            field=models.ManyToManyField(related_name='file_access', to='data.organization', verbose_name='organization'),
        ),
    ]
