# Generated by Django 5.0.6 on 2024-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_fileaccess_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
