# Generated by Django 5.0.6 on 2024-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_share_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgconright',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userconright',
            name='role',
        ),
        migrations.AddField(
            model_name='orgexerright',
            name='role',
            field=models.CharField(choices=[('A', 'Approver'), ('C', 'Contributer'), ('O', 'Observer'), ('S', 'Selfdefined'), ('U', 'Undefined')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='userexerright',
            name='role',
            field=models.CharField(choices=[('A', 'Approver'), ('C', 'Contributer'), ('O', 'Observer'), ('S', 'Selfdefined'), ('U', 'Undefined')], default='U', max_length=1),
        ),
    ]
