# Generated by Django 5.0.6 on 2024-07-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_comment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconright',
            options={'ordering': ['user', 'con']},
        ),
        migrations.AlterUniqueTogether(
            name='userconright',
            unique_together={('user', 'con')},
        ),
        migrations.AddField(
            model_name='orgconright',
            name='staff',
            field=models.ManyToManyField(related_name='org_con_rights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconright',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_rights', to=settings.AUTH_USER_MODEL),
        ),
    ]
