# Generated by Django 5.0.6 on 2024-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_fileaccess_is_public_file_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgexerright',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexerright',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
