# Generated by Django 5.0.6 on 2024-07-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_share_between_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exers', to='data.contract', verbose_name='contract'),
        ),
    ]
