# Generated by Django 5.0.6 on 2024-07-15 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_invitation_options_invitation_inviter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 14, 8, 23, 559796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='<function uuid4 at 0x000001C12B519D00>', editable=False, max_length=64, unique=True),
        ),
    ]
