# Generated by Django 5.0.6 on 2024-07-18 08:16

import data.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_invitation_expired_at_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 8, 16, 26, 148908, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=data.models.set_token),
        ),
        migrations.AlterField(
            model_name='share',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
