# Generated by Django 5.0.6 on 2024-07-18 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_invitation_options_alter_invitation_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 8, 18, 36, 23943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='share',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
