# Generated by Django 5.0.6 on 2024-07-19 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_comment_time_alter_invitation_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 10, 26, 5, 297388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='UserConRight',
        ),
    ]
