# Generated by Django 5.0.6 on 2024-07-22 11:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_invitation_expired_at_delete_userconright'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 11, 54, 31, 331218, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orgconright',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_chief', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgconright',
            name='staff',
            field=models.ManyToManyField(related_name='con_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
